version: '3.9'

services:
  # PostgreSQL Database
  db:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: extension_factory
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - app_network

  # Redis for Celery
  redis:
    image: redis:alpine
    container_name: redis_cache
    ports:
      - "6379:6379"
    networks:
      - app_network

  # Backend Service
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend_service
    depends_on:
      - db
      - redis
    env_file:
      - .env
    ports:
      - "5000:5000"
    restart: always
    volumes:
      - ./backend:/app
    networks:
      - app_network

  # Frontend Service
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend_service
    depends_on:
      - backend
    env_file:
      - .env
    ports:
      - "3000:80"
    restart: always
    volumes:
      - ./frontend:/app
    networks:
      - app_network

volumes:
  db_data:  

networks:
  app_network:  
